# Tensors

In [1]:
import torch
import numpy as np

In [2]:
# Tensors are very similar in operation to numpy arrays
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [15]:
# Can convert numpy to tensor and vice versa
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [16]:
# Similar operations as numpy
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [17]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.0033, 0.3708],
        [0.0984, 0.0375]])

In [18]:
# All familiar here
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [22]:
tensor = rand_tensor
tensor.shape

torch.Size([2, 3])

In [23]:
tensor.dtype

torch.float32

In [29]:
# Something new: what device the tensor is stored on
tensor.device

device(type='cpu')

In [43]:
# Move tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
tensor.device

device(type='cuda', index=0)

In [44]:
# Standard numpy indexing:
tensor = torch.ones(4, 4)
first_row = tensor[0]
first_col = tensor[:, 0]
last_col = tensor[..., -1]
# and standard numpy broadcasting
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [45]:
# Concatenate sequence of tensors (see also torch.stack)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [54]:
# Matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
assert (y1 == y2).all()
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [56]:
# Can specify output tensor
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)
y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [59]:
# Element-wise product (just like numpy)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
assert (z1 == z2).all() and (z1 == z3).all()
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [62]:
# Single-value tensor
agg = tensor.sum()
agg

tensor(12.)

In [63]:
# Can convert to python numerical using item()
agg = agg.item()
agg

12.0

In [66]:
# In-place operations on tensors are denoted by a suffix of _ (see also: copy_(), t_())
# Advantage: save some memory. Problem: immediate loss of history. Use is discouraged.
tensor.add_(5)
tensor

tensor([[16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.],
        [16., 15., 16., 16.]])

In [71]:
# Tensors on the CPU and numpy arrays can share underlying memory:
t = torch.ones(5)
n = t.numpy()
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [72]:
t.add_(5)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([6., 6., 6., 6., 6.])
n: [6. 6. 6. 6. 6.]


In [73]:
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]


In [74]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
